### ISSUE TITLE
Layout not found when using artisan queue:work

### ISSUE THREAD

**Issue by yonex68** [Z3d0X/filament-fabricator#111]
Hi!

I'm encountering a strange issue, as the "php artisan queue:work" command always fails when adding a job to the default queue:

`Exception: Filament Fabricator: Layout 'default' not found in file C:\xampp\htdocs\filament-test-export\vendor\z3d0x\filament-fabricator\src\Http\Controllers\PageController.php on line 31`

The job is using [spatie/laravel-export](https://github.com/spatie/laravel-export) which crawls the urls of the website.
When using the commands "php artisan queue:work --once" and "php artisan queue:listen", everything is fine, but running "php artisan queue:work" will throw the exception above, although the layout has been created by running "php artisan filament-fabricator:layout DefaultLayout".

Do you have any clue of what can cause this error?

Thx!

**Comment by Z3d0X** [comment]
This was fixed in `v2.0.3` pls update your plugin version

**Comment by yonex68** [comment]
All plugins are up to date... Still have the error:

![image](https://github.com/Z3d0X/filament-fabricator/assets/47473615/bef3446f-3cda-4e4a-aa15-4e70efc018cd)

![image](https://github.com/Z3d0X/filament-fabricator/assets/47473615/edef1db4-e346-4c75-8af6-99bd6e92b551)

**Comment by yonex68** [comment]
I've put some logs in Http\Controllers\PageController.php:

![image](https://github.com/Z3d0X/filament-fabricator/assets/47473615/7d7bbb36-c53f-4d79-9e5c-42419dbf1e60)

And the getLayoutFromName('default') function returns _null_

**Comment by Z3d0X** [comment]
`composer show z3d0x/filament-fabricator`

**Comment by yonex68** [comment]
![image](https://github.com/Z3d0X/filament-fabricator/assets/47473615/580dca79-a3b9-45a8-9d9c-2f6b0b54a7ed)

**Comment by jydevgit** [comment]
I have exactly the same bug in a similar environment.. have you an idea?
